### ISSUE TITLE
hot key doesnt work on mac

### ISSUE THREAD

**Issue by hololeo** [LSXPrime/ProseFlow#1]
Ctrl+J (or any other combo) is not recognized at all by the app. 

I gave the app permissions as well. this did not change anything

is there a log file to look at?

**Comment by advaitian** [comment]
Just skip the initial setup and open the application. The hot key will work after that. The only issue is during the initial setup steps, which you can skip.

**Comment by advaitian** [comment]
now there is a log file ~/Library/Application Support/ProseFlow/logs/proseflow-202509.log
but  Dashboard or history are still shows nothing.

<img width="1593" height="804" alt="Image" src="https://github.com/user-attachments/assets/1b4a98fb-d068-4c73-98d2-f18980ca5b88" />

**Comment by LSXPrime** [comment]
I just pushed a small commit that addresses the hotkey issues during onboarding, disables hardware monitoring on ARM64 macOS systems (with UI updates to reflect this), and fixes hotkey handling on non-US keyboards. If you'd like to test it from source, follow the ["Building from Source"](https://github.com/LSXPrime/ProseFlow?tab=readme-ov-file#-building-from-source) instructions in the README but run using `dotnet run -f net8.0-macos`.

To re-show the onboarding screen for testing, open the database file (`~/Library/Application Support/ProseFlow/proseflow.db`) in any SQLite3 editor like [SQLite Browser](https://sqlitebrowser.org/dl/), navigate to the `General Settings` table, set the `IsOnboardingCompleted` value to `0`, and then close the application if it was running and start the app using the previous steps.

**Comment by advaitian** [comment]
New version having this issue:
Directory ~/.config/ProseFlow/logs/ and ~/Library/Application Support/ProseFlow/logs/ exist, but both are empty.


<img width="405" height="162" alt="Image" src="https://github.com/user-attachments/assets/41b50b75-29ad-49d2-bd44-1130d2bb651d" />

**Comment by LSXPrime** [comment]
Good morning,  

I apologize for the delayed response — I wanted to ensure robust fallback implementations for the clipboard before finalizing the commit. After significant refactoring, I've now implemented three services (Avalonia → Native Shell → TextCopy) to reliably access the clipboard and retrieve selected text.  

Could you please test the latest update, v0.2.0, to verify if the issue persists? You can update directly from the "About" screen within the app.  

As a small adjustment, I've added a brief delay of approximately 200ms before copying the selected text, to allow the active window to regain focus after the floating menu window is closed.  


And if you have a moment, I’d like to ask a side request that could potentially reduce the macOS binary size by up to 50%. The macOS builds currently include a nested or duplicated application bundle, as shown in the folder structure below. 

My request is to download the macOS portable version, extract the nested `ProseFlow.app` from the base `ProseFlow.app` folder, and test running both versions independently to see if either works without the other. 
While no online documentation mentions duplicated bundles, .NET appears to generate them automatically during the build process.

Thanks for your help!
```
└───ProseFlow.app
    └───Contents
        │   Info.plist
        │
        ├───MacOS
        │   │   ProseFlow (Main Executable)
        │   │   UpdateMac (Updater Executable)
        │   │   ProseFlow.dll (Main application library)
        │   │   ProseFlow.runtimeconfig.json
        │   │
        │   │   (Many .NET assemblies for Avalonia, Microsoft, etc.)
        │   │   (Many native .dylib libraries for .NET runtime, Skia, etc.)
        │   │
        │   ├───cs, de, es, fr, ... (Folders for localized resources)
        │   │
        │   ├───ProseFlow.app (A nested application bundle)
        │   │   └───Contents
        │   │       │   Info.plist
        │   │       │
        │   │       ├───MacOS
        │   │       │       ProseFlow (Executable)
        │   │       │
        │   │       └───MonoBundle
        │   │           │   (A large collection of .NET assemblies and .dylib files)
        │   │           │
        │   │           └───runtimes
        │   │               └───osx-x64
        │   │                   └───native
        │   │                           (Native libraries for LLamaSharp: libllama.dylib, etc.)
        │   │
        │   └───runtimes
        │       └───osx-x64
        │           └───native
        │                   (Duplicate native libraries for LLamaSharp)
        │
        └───Resources
                logo.icns
```

**Comment by advaitian** [comment]
With the updated version, the same issue persists. However, instead of reporting only "Processing..." , it reports  for example, saying "Processing 'proofread'".

**Comment by LSXPrime** [comment]
1. Are you using a local provider? If so, please test with a cloud provider.
2. If you can run it from source, please add breakpoints to the following lines and report the point it reaches before stopping.

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Infrastructure/Services/Os/Clipboard/ClipboardService.cs#L146

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Infrastructure/Services/Os/Clipboard/ClipboardService.cs#L168

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Infrastructure/Services/AiProviders/LocalProvider.cs#L35

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Infrastructure/Services/AiProviders/LocalProvider.cs#L49

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Infrastructure/Services/AiProviders/LocalProvider.cs#L104

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Infrastructure/Services/AiProviders/LocalProvider.cs#L154


https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L130

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L169

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L184

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L348

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L357

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L368

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L381

https://github.com/LSXPrime/ProseFlow/blob/37e8fd2d3520dff543176413c4f06f562b2ba7c7/ProseFlow.Application/Services/ActionOrchestrationService.cs#L389

**Comment by advaitian** [comment]
Same Error for both Local and Cloud providers.

<img width="382" height="166" alt="Image" src="https://github.com/user-attachments/assets/45c7b40b-0f70-41d9-86bd-0e67ad3b285e" />

**Comment by LSXPrime** [comment]
Good evening,

If you were still interested in the application, I've just released **v0.3.0**, which contains another try to tackle this by giving the system some time to process the copy text request (Meta + C keys on MacOS - Control + C keys on Win/Linux), in addition to new generation mode which will make it more valuable in another way. You can safely download the latest version from the website or GitHub releases.

This isn't just a bug-fix release, by the way—it's an update packed with new functionality. Just to give you a heads-up on what you'll be getting:

*   **Dynamic Action Templates:** This is the biggest change. You can now create actions with placeholders (e.g., `Translate this into [language]`). When you run it, ProseFlow will pop up a quick form to ask for the language, turning your actions into powerful, reusable tools.
*   **Generation Mode:** The app now intelligently detects if you have text selected. If you trigger the hotkey without a selection, it enters "Generation Mode," letting you create content from scratch without leaving your current window.
*   **A bunch of UX improvements:** I've added features like bulk action management (select/delete/move multiple actions at once) to make organizing your workflow much easier.

Let me know if you got any progress.
